@ECHO OFF
START /REALTIME /B TASKKILL /IM uu.exe /T /F
START /REALTIME /B TASKKILL /IM WOTBox.exe /T /F
START /REALTIME /B TASKKILL /IM LOLBox.exe /T /F
START /REALTIME /B TASKKILL /IM WorldOfTanks.exe /T /F
START /REALTIME /B TASKKILL /IM LolClient.exe /T /F
START /REALTIME /B TASKKILL /IM lol.launcher_tencent.exe /T /F
START /REALTIME /B TASKKILL /IM BaiduGs.exe /T /F
START /REALTIME /B TASKKILL /IM uu_ball.exe /T /F
START /REALTIME /B POWERCFG /S a1841308-3541-4fab-bc81-f71556f20b4a
